name: Deploy Assets to CDN

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Gzip Plugin Files
        run: find ./dist \( -name "*.js" -o -name "*.css" \) -exec gzip -k "{}" \;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # change to secret when we can configure org / repo settings
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # change to secret when we can configure org / repo settings
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }} # change to secret when we can configure org / repo settings

      - name: Deploy Theme - Gzip Files
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_PROD }}/${{ secrets.AWS_FOLDER_PATH }} --exclude '*' --include '*.gz' --delete --content-encoding 'gzip'

      - name: Deploy Theme - Other Files
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_PROD }}/${{ secrets.AWS_FOLDER_PATH }} --exclude '*.gz' --delete
