name: Build Test
on: [push]
jobs:
  build:
    name: Build, Lint, and Test project on Node ${{ matrix.node }} and ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x'] # '16.x',
        os: [ubuntu-latest] # macOS-latest windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node v${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Deploying application to Amazon S3
      # uses: dvelasquez/deploy-s3-action@main
      # with:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      #   AWS_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
      #   BUCKET_PATH: '/rds'
      #   DIST_LOCATION_CODE: ./dist

      # - name: Deploying assets to S3
      #   uses: jeanlescure/react-deploy-to-s3-action@main
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      #     SOURCE_DIR: dist # optional: defaults to public
      #     DEST_DIR: rds
