name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
        # run: npm ci
      - run: yarn build
        # run: npm run build
      - run: yarn publish --access public
        # run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.RDS_NPM_TOKEN}}
