name: S3 Deployment
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.2.0

        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          delete-removed: false
          no-cache: true
          private: true
          # files-to-include: '.*/*,*/*,**'
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Install
#         run: npm ci

#       - name: Build App
#         run: npm run build

#       - name: S3/CloudFront Deploy
#         uses: staevs/s3-deploy-action@v1.2.2
#         if: success()
#         with:
#           args: --acl public-read --follow-symlinks --delete
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#           AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           S3_SOURCE_DIR: 'dist'
#           S3_DESTINATION_DIR: 'rds'

# - name: Deploying application to Amazon S3
# uses: dvelasquez/deploy-s3-action@main
# with:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#   AWS_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
#   BUCKET_PATH: '/rds'
#   DIST_LOCATION_CODE: ./dist
